# paths:
#   - 'migrations/**'
#   - 'projects/server/**'
#   - 'projects/core/constants/**'
#   - 'projects/core/methods/**'
name: "Bump version"
on:
  push:
    branches:
      - beta
concurrency: prerelease
jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      # Bump version/tag
      - name: Bump version/tag
        id: taggerFinal
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "main"
          PRERELEASE: true
          WITH_V: true

      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: "0"

      # Changelog
      - name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.taggerFinal.outputs.new_tag }}
      ##
      - name: Commit Changelog to repository
        uses: stefanzweifel/git-auto-commit-action@v4.13.0
        with:
          commit_message: 'docs(changelog): Update changelog [skip ci]'
          file_pattern: CHANGELOG.prerelease.md

      # Version
      - name: Bump version file
        id: bump-tag-file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "version-prerelease.json"
          json: '{"version": "${{ steps.taggerFinal.outputs.new_tag }}" }'
          dir: "./"
      ##
      - name: Commit version to repository
        uses: stefanzweifel/git-auto-commit-action@v4.13.0
        with:
          commit_message: 'build(version): Bump version [skip ci]'
          file_pattern: version-prerelease.json

      # Release
      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.taggerFinal.outputs.new_tag }}
          release_name: Release ${{ steps.taggerFinal.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.changes }}
          